stop_words = ['il', 'lo', 'la', 'i', 'le', 'gli', 'è', 'tu', 'tuo', 'tua', 'suo', 'sue',
			  'suoi', 'sua', 'loro', 'lei', 'quale', 'quali', 'questa', 'questo', 'cosa',
			  'che', 'non', 'per', 'come', 'egli', 'voi', 'del', 'della', 'così',  'più',
			  'con', 'col', 'cui', 'una', 'qual', 'fu', 'fosse', 'era', 'lui', 'quello',
			  'senza', 'alla', 'dove', 'già', 'ogni', 'vostra', 'vostro', 'vostri', 'vostre',
			  'nostro', 'nostra', 'nostre', 'nostri', 'altro', 'altra', 'altre', 'altri',
			  'molto', 'molta', 'molte', 'molti', 'nel', 'ciò', 'quella', 'bene', 'ben',
			  'ella', 'disse', 'sopra', 'noi', 'alessandro',  'ser', 'esser', 'essere', 'fa', 'fare',
			  'alcuna', 'alcun', 'alcuno', 'ora', 'far', 'quando', 'pietro', 
			  'filippo', 'alberto', 'ferondo', 'gianni', 'fatto',
			  'ché', 'ricciardo', 'riccardo', 'chichibio',
			  'bruno', 'gisippo', 'federigo', 'mai', 'ma', 'poi', 'aveva', 'mio', 'mia', 'masetto',
			  'rinaldo', 'nella', 'nello', 'lor', 'erano', 'lor', 'gerbino', 
			  'gabriotto', 'tanto', 'tanti', 'tante', 'tanta', 'cose', 'delle',
			  'giosefo',
			  'quanto', 'dentro', 'tutto', 'tutta', 'tutti', 'tutte',
			  'nelle', 'giù', 'assai', 'avea', 'dire', 'avendo', 'essendo', 'guiglielmo',
			  'anichino', 'fece', 'sia', 'ancora', 'martuccio', 'efigenia', 'antigono', 'giannetta',
			  'uno', 'avessi', 'quivi', 'sofronia', 'chi',
			  'giacomino', 'ghino', 'allora', 'angiulieri', 'geri', 'pavia',
			  'puccio', 'quindi', 'pirro' , 'perché', 'salabaetto', 'giannotto', 'dico',
			  'dall', 'dal', 'son', 'qui', 'hai', 'sono', 'aver', 'all', 'essi', 'due', 'sapere', 'alle', 'quelle',
			  'queste', 'due', 'tra', 'fine', 'dell', 'del', 'avesse', 'hanno', 'oltre', 'quantunque', 'diceva', 'dice',
			  'tre', 'quegli', 'fatti', 'stato', 'stata', 'dalla', 'agli', 'avere', 'alquanto', 'adunque', 'fanno', 'furono',
			  'cominciò', 'fossero', 'andò', 'incominciò',' solamente', 'degli', 'fatta', 'ebbe', 'coloro', 'questi', 'miei',
			  'nell', 'secondo', 'elle', 'solamente', 'dopo', 'pero', "panfilo", "neifile", "filomena", "dioneo", "fiammetta",
	"emilia", "filostrato", "lauretta", "elissa", "pampinea", 'colei', 'quel', 'state', 'stati', 'stato', 'stata', 'dello']

narrators = ["panfilo", "neifile", "filomena", "dioneo", "fiammetta",
	"emilia", "filostrato", "lauretta", "elissa", "pampinea"]

